### PR TITLE
Source maps flags conditional for pre/post 0.12

### PR DESCRIPTION
**Pull request by nwolverson**
#343

### CODE REVIEW

**Comment by nwolverson** [comment]
Heck of a lot of integration tests failing already on master, I don't feel like diving into that just now

**Comment by hdgarrood** [comment]
I think #340 should have addressed many of those failures. Would you mind rebasing?

**Comment by nwolverson** [comment]
Happily, but will be Monday at earliest until I'm in the only of my pc.

**Comment by hdgarrood** [comment]
Sure thing, no rush!

**Comment by nwolverson** [comment]
Rebased and CI passed

**Comment by hdgarrood** [comment]
Looks good, thanks!

**Comment by bqv** [comment]
Can this be pushed into a release please?

**Comment by hdgarrood** [comment]
I've just published v12.3.1 which includes this fix. Sorry for the delay!

**Pull request merged**
