### PR TITLE
Transitioning to 0.12.0

### PR DESCRIPTION
**Pull request by jacereda**
This is really WIP.

I updated dependencies because i ran into https://github.com/NixOS/nixpkgs/issues/40406 (I'm still trying to figure out if it's a problem in `node2nix`).

### CODE REVIEW

**Comment by nwolverson** [comment]
This appears to ignore the existing 0.12 related PRs 👎 
In particular I think https://github.com/purescript-contrib/pulp/pull/340 is good to go

**Comment by jacereda** [comment]
I was well aware of #340 and I was assuming it was going to be merged well before this was ready. This one addresses different problems.

**Comment by nwolverson** [comment]
Fair enough, that wasn't clear to me from the comment, it sometimes happens that people make PRs without being aware what's there already.

**Comment by jacereda** [comment]
I integrated #340 and I'd also like to see #344 and #345 merged, should I merge those here?

**Comment by hdgarrood** [comment]
I’d rather deal with different PRs separately, actually.

**Comment by hdgarrood** [comment]
There's too much going on here for my liking. Updating the npm dependencies is probably worth doing, but that really ought to be done on its own, for instance. There's already a PR for using the new `--codegen` flags as well, so I'd prefer to leave that out of this one.

**Pull request closed without merging**
