### PR TITLE
Allows --skip-entry-point to be given to build when bundling with --to.

### PR DESCRIPTION
**Pull request by damncabbage**
(Addresses #130.)

### CODE REVIEW

**Comment by hdgarrood** [comment]
LGTM :+1:

**Comment by damncabbage** [comment]
halp (regarding https://github.com/bodil/pulp/pull/137/files#diff-b0388a7437dba25ce5aabac93ce75805R139)

```
SyntaxError: Unexpected token ILLEGAL
    at Object.exports.runInThisContext (vm.js:53:16)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:435:26)
    at node.js:578:27
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
Expected exit code 0 but got 1.
  Error: Command failed: C:\windows\system32\cmd.exe /s /c "node -e 'var o = require("./out"); o.Main.main();'"
  [eval]:1  
  'var  
  ^^^^  

  SyntaxError: Unexpected token ILLEGAL  
      at Object.exports.runInThisContext (vm.js:53:16)  
      at Object.<anonymous> ([eval]-wrapper:6:22)  
      at node.js:578:27
```

(I don't have a Windows anything to test this on.)

**Comment by bodil** [comment]
Windows doesn't seem to cope with the single quoted JS code. You might need to write the code out to a temp file and execute it as a script, or maybe there's some other way to quote it. I don't know, this sort of thing is exactly why I shun Windows. :)

**Comment by hdgarrood** [comment]
Afaik double quotes on Windows behave like single quotes on Unices. I think there is an example in Pulp.Shell too

**Comment by bodil** [comment]
Note the command line: the single quotes are there because they're already inside double quotes. So maybe converting them to escaped double quotes work? Idk.

**Comment by bodil** [comment]
Oh, yes, and there are double quotes inside the single quotes inside the double quotes.

**Comment by hdgarrood** [comment]
:scream:

Maybe this will help? http://stackoverflow.com/questions/7760545/cmd-escape-double-quotes-in-parameter#7760618

**Comment by damncabbage** [comment]
I got around the node quoting problem by swapping the quotes. I'm now in a spot where node (on Windows) isn't finding the resulting generated `out.js` file after I've `--then`-appended the `module.exports = PS;` line.

Current error:

```
integration tests

    1) pulp build --skip-entry-point --to

  0 passing (5s)
  1 failing

  1) integration tests pulp build --skip-entry-point --to:
     Error: ENOENT: no such file or directory, open 'C:\Users\appveyor\AppData\Local\Temp\1\pulp-test-1151128-2588-1e5v0eu\out.js'
      at Error (native)
      at Object.fs.openSync (fs.js:549:18)
      at Object.fs.readFileSync (fs.js:397:15)
      at file (C:/projects/pulp/test-js/sh.js:34:23)
```

To be clear, I've tried:
- `var o = require('./out'); o.Main.main();`
- `var o = require(require('path').join(process.cwd(), 'out')); o.Main.main();`
- `var o = require(require('path').join(process.cwd(), 'out.js')); o.Main.main();`  
  (What I have currently.)

**Comment by hdgarrood** [comment]
I don't think it's getting that far, I think it's failing on `assert.exists(path.join(temp, 'out.js'));` (just beforehand), based on the stack trace you're seeing.

You might find it useful to insert an `argsParserDiagnostics` into `main` inside `src/Main.purs`, to see how pulp is interpreting your command line arguments.

**Comment by damncabbage** [comment]
That assertion was a last-minute addition. An earlier failure is more revealing:

```
  1) integration tests pulp build --skip-entry-point --to:
     Command failed: C:\windows\system32\cmd.exe /s /c "node -e "var o = require(require('path').join(process.cwd(), 'out.js')); o.Main.main();""
module.js:339
    throw err;
    ^

Error: Cannot find module 'C:\Users\appveyor\AppData\Local\Temp\1\pulp-test-1151127-936-oqhlkn\out.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at [eval]:1:9
```

Regardless, with my last commit (bc70e17) now using full paths for every `out.js` reference, it's still falling over. I'm stuck.

**Comment by damncabbage** [comment]
:rewind: Ready for review.

The test solution is a little more, uh, precarious than I'd like (unquoted `echo`), but it works cross-platform, and is at least short and understandable.

In one of the [intermediary builds](https://ci.appveyor.com/project/bodil/pulp/build/1.0.106#L1038), @hdgarrood and I discovered that the output stream in `Pulp.Build.bundle` was being left open, causing the build to fail in AppVeyor with a `cannot access the file because it is being used by another process` error. This is now fixed in acef829.

**Comment by hdgarrood** [comment]
:fireworks:

**Comment by bodil** [comment]
omg Windows.

So this is good to merge?

**Comment by hdgarrood** [comment]
I think so.

**Comment by bodil** [comment]
Make it so!

**Pull request merged**
