### PR TITLE
Topic/psc release

### PR DESCRIPTION
**Pull request by ethul**
PR pertaining to issue #13.

This does not come without caveats however. For one, `psc-release` relies on a file naming convention of the Github asset files. I am not sure if this is a same assumption to make. Perhaps @paf31 can chime in on this matter. Basically, I am referring to ethul/psc-release#2, and if it's safe to assume the mapping from platform name to PureScript asset filename.

Also, @bodil, I think the addition to the README here may need a bit of tweaking. If you think this PR is a good direction to go, perhaps it would be worth discussing the installation procedure that is described there.

In any case, this is more or less a first attempt. I am open to any suggestions, feedback, or comments.

### CODE REVIEW

**Comment by bodil** [comment]
Hmm, I'd like to play around with this a bit more before merging it, if you don't mind, I've got some ideas I want to try out on it.

Hopefully we can rely on the naming convention, though, right @paf31? :)

**Comment by paf31** [comment]
Yes, the naming schema will be fixed, so you can hard code it.

**Comment by ethul** [comment]
@bodil Take you time, no rush.

@paf31 thanks!

**Comment by paf31** [comment]
Just to be clear, it's `OSNAME.(sha|tar.gz)`, so
- `win64.tar.gz`
- `macos.tar.gz`
- `linux64.tar.gz`

etc.

**Comment by ethul** [comment]
Great! Thanks @paf31

**Comment by hdgarrood** [comment]
I'm going to close this PR just because it's too old to do anything with now.

In the meantime, it may be worth noting that https://www.npmjs.com/package/psvm now exists, and seems to solve the same problem. In fact Pulp uses it in its build scripts now, and it also plays quite well with normal purescript projects built by Pulp too.

**Pull request closed without merging**
