### PR TITLE
Remove Pulp.Rebuild and associated code.

### LINKED ISSUE #164: Slow build with no changes without --force
Reliably (at least for this project? not tested extensively) my builds are super slow if I don't specify `--force` when there are no changes (it's also slow when there are changes but less obvious). Running the command anyway and letting `psc` find no changes is way quicker. 

System: OSX

```
$ pulp -v
Pulp version 7.0.0
psc version 0.8.0.0
```

Timings after a previous build already completed:

```
$ time pulp build 
* Project unchanged; skipping build step.

real    0m42.227s
user    0m24.573s
sys 0m19.674s
```

```
$ time pulp build --force
* Building project in /Users/nicholaw/git/atom-ide-purescript
* Build successful.

real    0m1.295s
user    0m3.224s
sys 0m0.533s
```

### PR DESCRIPTION
**Pull request by hdgarrood**
Fixes #164 and #146. See also discussion on #146. @bodil, it's up to you whether we go ahead with this approach or try something else. Right now, this option seems the most sensible to me.

### CODE REVIEW

**Comment by bodil** [comment]
Yes, I'm in favour. Let me just fix the tests first. :)

**Comment by hdgarrood** [comment]
Don't worry, I've already done it, and I'm just about to push one myself :)

edit: where "one" = a fix for the tests.

**Comment by hdgarrood** [comment]
Ok, rebased and fixed (hopefully).

**Comment by hdgarrood** [comment]
Oh, I guess you meant the tests failing on Windows re the psa thing, `.bat` vs `.cmd`? Ok, I haven't done anything about that. There was another error in my original attempt which I have fixed here now - I left the `--force` flags in for `pulp build`, and because they are now unrecognised, I think they were being passed through to `psc`, which also didn't recognise them, and so it errored.

**Comment by hdgarrood** [comment]
@bodil good to go?

**Comment by bodil** [comment]
Hmm, `pulp browserify` still uses `--force` though?

**Comment by bodil** [comment]
Ah, that's still there. Let's merge, then!

**Pull request merged**
