### PR TITLE
Switch to purescript-node-child-process

### PR DESCRIPTION
**Pull request by hdgarrood**
The bower.json diff is a mess because I decided to sort the dependencies alphabetically. The only actual difference is that now, it also includes `purescript-node-child-process`.

The bower.json file currently uses the most recent commit SHA from the purescript-node organisation's repository. This is because the bower registry points to the original creator's repository, and he hasn't yet responded to a request to transfer it.

### CODE REVIEW

**Comment by hdgarrood** [comment]
`purescript-node-child-process` has been transferred so we're using the published bower version now :)

**Comment by hdgarrood** [comment]
Actually wait a bit, I'm going to release a breaking change to this package in a moment.

**Comment by hdgarrood** [comment]
Oops, that change to Main wasn't meant to be in there. Will fix that later.

**Comment by hdgarrood** [comment]
This is good to go now, I think. The tests pass on my Windows VM so we can chalk the CI failure up to bower/appveyor.

**Comment by bodil** [comment]
If you rebase, I'll merge. :)

**Comment by hdgarrood** [comment]
Ok, will do :) I just need to add the binding to `exec` to `purescript-node-child-process` first.

**Comment by bodil** [comment]
Oh, right, you moved it. I'm not sure my implementation is suitably generic (it doesn't take any options, for one); feel free to leave it in Pulp if you like.

**Comment by hdgarrood** [comment]
Yeah, generally I don't mind if the bindings in `purescript-node` don't fully cover the Node apis that they're wrapping at first, but I am going to try to support some of the options. I'm on a bit of [a drive to get people to stop using the FFI so much](http://harry.garrood.me/blog/when-to-use-the-purescript-ffi/) at the moment, so I'm happy to take a bit more time on this.

**Comment by hdgarrood** [comment]
The Windows tests work on my VM as of the most recent commit, despite failing on appveyor (for the normal reason... sigh).

I find it mildly horrifying that the most recent commit makes the tests pass on Windows. On the commit before, they passed on Linux but failed on Windows, and I have no idea why. Perhaps I don't understand how scoping or hoisting works in JS, or perhaps even if statements...

Anyway they work on my Windows VM now, so I think this is good to go.

**Comment by hdgarrood** [comment]
Oh wait, no, pretty much all the tests are still broken on Windows. I'm going to call it a day.

**Comment by hdgarrood** [comment]
I worked out what was going on: it was a bug in `purescript-node-child-process`, which I've now fixed and published as v0.4.1. I think this is good to go now.

**Comment by bodil** [comment]
Then, we merge!

**Comment by hdgarrood** [comment]
:)

**Comment by bodil** [comment]
I keep getting `* ERROR: Node_ChildProcess.fork is not a function` when I go `pulp -w test` after merging this. :(

**Comment by hdgarrood** [comment]
Oops - this is my fault. Sorry. https://github.com/purescript-node/purescript-node-child-process/commit/53e0be5048791ea195fa532f1ee14a504a26bb7b

**Comment by bodil** [comment]
I wish `--watch` was even remotely testable. :(

**Comment by hdgarrood** [comment]
yeah :( `fork`, on the other hand, _is_ testable, so I have no excuse here.

**Comment by hdgarrood** [comment]
I'm going to bump `node-child-process` and release 6.1.1.

**Comment by hdgarrood** [comment]
6.2.1, sorry.

**Comment by hdgarrood** [comment]
Ok, 6.2.1 is out, which should fix this problem.

**Comment by bodil** [comment]
Thanks. 👍 :shipit: 👍

**Pull request merged**
