### PR TITLE
0.9 compatibility

### PR DESCRIPTION
**Pull request by hdgarrood**
WIP, this gets us most of the way to #211.

### CODE REVIEW

**Comment by hdgarrood** [comment]
I'd like feedback on the proposed new bower.json generated by `pulp init`, does that seem sensible? Right now it depends on `console` as a normal dependency, and `psci-support` as a devDependency. cc @paf31 @garyb

**Comment by garyb** [comment]
Makes sense :+1:

**Comment by nwolverson** [comment]
Just tried this with the RC/0.9.0, got this message:

```
* This version of Pulp requires version 0.9.0.0 of the PureScript compiler or higher.
* Your installed version is 0.9.0.
```

I guess the number of components changed

**Comment by hdgarrood** [comment]
Thanks @nwolverson, should be fixed now.

**Comment by hdgarrood** [comment]
Closing because I've screwed up the git history somehow. This works now anyway so I'm just going to put it into master.

**Pull request closed without merging**
