### PR TITLE
Remove engine

### LINKED ISSUE #143: --runtime/-r option no longer working?
I used to use this with `-r cat` when running tests to output the test JS to a file, but it doesn't seem to do anything any more.

### PR DESCRIPTION
**Pull request by hdgarrood**
Fixes #143.

Given that this will be a breaking change, maybe we could do #144 as well before the next release?

### CODE REVIEW

**Comment by ttbodil** [comment]
Could you add "closes #143" to the commit message? Makes it easier to figure out the changelog.

**Comment by ttbodil** [comment]
Could you add "closes #143" to the commit message? Makes it easier to figure out the changelog.

**Comment by hdgarrood** [comment]
Done :)

**Comment by bodil** [comment]
I really need to learn to stop posting from my work account. :person_frowning:

Anyway, let's merge!

**Pull request merged**
