### PR TITLE
Use psa if it's in the path

### PR DESCRIPTION
**Pull request by natefaubion**
Also adds a `--no-psa` flag to turn it off.
#157

### CODE REVIEW

**Comment by hdgarrood** [comment]
Looks great, but do you think you could add some tests? I think the following should cover it:
- without `--no-psa`, it should use `psa`
- without `--no-psa`, and if `psa` is not found, it should use `psc`
- with `--no-psa`, it should use `psc` and not attempt `psa`

One way to achieve this could be to add a directory `test-js/bin`, add a basic script in there called `psa` which simply exits with a particular message or something, and then add that directory to the PATH at the beginning of the relevant tests? Don't hesitate to ignore this suggestion if you can think of a better way though.

**Comment by natefaubion** [comment]
I'm actually having trouble running the tests when I have psa in my own path. Most of the build related tests fail with the `psc` help message, yet I have no issues when actually using it to build projects.

**Comment by natefaubion** [comment]
For example:

```
  22) integration tests --force flag forces rebuild:
     Command failed: /bin/sh -c node "/Users/nathan/Sites/git/pulp/index.js" build --force
* Building project in /private/var/folders/5w/qbhh3b9510lb_nmwh52xr8qm0000gn/T/pulp-test-116018-36898-mvba6n
Usage: psc [FILE] [-f|--ffi ARG] [-o|--output ARG] [--no-tco] [--no-magic-do]
           [--no-opts] [-v|--verbose-errors] [-c|--comments]
           [-r|--require-path ARG] [-p|--no-prefix]
```

However, if I copy and paste that command in another shell for a project it works as expected.

**Comment by hdgarrood** [comment]
agh, that's annoying. Could you put a bit of logging in inside `Pulp.Exec.exec` perhaps, to see how `psc` is actually being called there?

Edit: oh, actually, you might want `Pulp.Exec.execQuiet`.

**Comment by natefaubion** [comment]
I don't know what going on :/ I put in some logging (I had to modify sh.js as well because it swallows stdout), and args are identical. Run through the integration tests I get failures, but when I run it with an identical command in the shell everything is fine.

**Comment by natefaubion** [comment]
Ohhh, duh! In `devDependencies` you have `purescript==0.7.6` which doesn't support the --json-errors flag :)

**Comment by hdgarrood** [comment]
It's a shame that `psc` (and the other tools) don't actually say which arguments were unrecognised. It seems it would save a lot of time in situations like this.

**Comment by hdgarrood** [comment]
In the meantime, maybe we should wait for psc 0.8 to be released?

**Comment by bodil** [comment]
Do we need a working `psa` to test that it's being invoked? Harry's `test-js/bin` trick sounds plausible to me. I'm just keen to have this feature now, without having to wait for 0.8 to release and percolate down to npm. :)

**Comment by hdgarrood** [comment]
Ah, right, yes. I guess we just need to somehow make sure that there's no "real" `psa` in the PATH when running the tests.

**Comment by natefaubion** [comment]
> without --no-psa, and if psa is not found, it should use psc

I don't know how I can ensure an executable named "psa" is not in the path _at all_ unless I called `exec` with an empty path, in which case the tests wouldn't work.

**Comment by hdgarrood** [comment]
Could we take all the required executables for the tests (I think that would be `bower`, `psc`, `psc-docs`), create symlinks to each of those in some extra (temporary?) folder, and then set the PATH to be only that directory at the start of the test suite?

**Comment by natefaubion** [comment]
> Could we take all the required executables for the tests (I think that would be bower, psc, psc-docs), create symlinks to each of those in some extra (temporary?) folder, and then set the PATH to be only that directory at the start of the test suite?

I mean, I'm probably not going to do that.

**Comment by natefaubion** [comment]
Like, I understand its a valuable test, but I don't really have the time to figure out how to do that within the confines of how this test suite is setup with all the promises, and generators and stuff.

**Comment by hdgarrood** [comment]
That's fair. We were vaguely planning to port the tests to PureScript at some point. It is admittedly very awkward, but I don't see any other way of testing this properly (and considering pulp's position in the purescript ecosystem, I really would like it to be tested properly).

**Comment by natefaubion** [comment]
As long as you don't mind synchronous functions and `shelljs`, then I'll add this as part of `run`. But if that's not acceptable, then I'd be happier to open an easier to test PR :)

**Comment by bodil** [comment]
Hold on, I'm attempting to implement a test. :)

**Comment by bodil** [comment]
OK, I accidentally merged it, and I broke all the Windows tests, but never mind. :)

**Comment by natefaubion** [comment]
Who uses Windows, anyway?

**Comment by bodil** [comment]
I was shocked and terrified to see the npm OS stats. Apparently you will be too. :)

**Comment by bodil** [comment]
Sigh, of course the Windows build ignores my PATH hacks: https://ci.appveyor.com/project/bodil/pulp/build/1.0.245#L1399

Can anyone spot an obvious way to fix this, or shall I just disable this test on Windows?

**Comment by hdgarrood** [comment]
I am fairly sure we want .cmd instead of .bat here - the npm distribution gives you psc.cmd (etc).

**Pull request merged**
